### PR TITLE
Add the hdr.husk flag to support the ability to reduce files without losing track of their POT

### PR DESCRIPTION
**Pull request by cjbackhouse**
I struggled to come up with a succint name/metaphor for this concept. Anyone want to dive into a thesaurus and come up with something better than `husk`?

### CODE REVIEW

**Comment by PetrilloAtWork** [comment]
I suggest `doNotDropMeOrYouWillRegretItForever`.
Never been great with names.

**Review by brucehoward-physics — APPROVED** [review]
One thing I noticed which is unrelated to this PR is that the constructor doesn't set an initial value for `first_in_file` and `first_in_subrun` even though everything else is set to a default value. Maybe this is aimed at someone other than @cjbackhouse, but if you know, is that on purpose?

With respect to this PR, I'm not the foremost SBN SR expert, but this change seems very non-controversial, as it just adds a field and sets it in the constructor to a default value.

(And with respect to `husk` I think it makes sense as a name.)

**Comment by cjbackhouse** [comment]
Re `first_in_file` and `first_in_subrun`, I think there is consensus to remove them, so this problem will eventually become moot anyway.

**Comment by cjbackhouse** [comment]
Updated the version and checksum. Not sure how I managed to build before without that happening...

**Comment by cjbackhouse** [comment]
trigger build

**Pull request merged**
