### PR TITLE
Update SRTrigger

### PR DESCRIPTION
**Pull request by gputnam**
Make SRTrigger a single instance in SRHeader. Change trigger_within_gate to be a double in us.

### CODE REVIEW

**Comment by cerati** [comment]
requested same reviewers as parent PR

**Review by jacoblarkin — APPROVED** [review]
Approving since the code looks good and I think this is a good idea, but like with the sbncode PR I'll defer to Gianluca on this particular change since I don't know if there was a reason to make the trigger a vector rather than a single value.

**Review by PetrilloAtWork — COMMENTED** [review]
It's good.
@gputnam: I wonder what drove the choice to turn the time difference into a floating point type.

**Comment by PetrilloAtWork** [comment]
> Approving since the code looks good and I think this is a good idea, but like with the sbncode PR I'll defer to Gianluca on this particular change since I don't know if there was a reason to make the trigger a vector rather than a single value.

In fact, I and @gputnam had interacted before he started this, and I endorsed the change. There is always a single global trigger (it's the one that makes the decision). Even if there were more trigger objects around, one of them is The One; and it would then make sense to keep the other "triggers" in their own data structure.

**Pull request merged**
