### PR TITLE
Feature/etyley caf units

### PR DESCRIPTION
**Pull request by etyley**
Updating the documentation in the Standard Record headers to make the energy units consistent. This also corrects and adds in some missing units.

### CODE REVIEW

**Review by cjbackhouse — DISMISSED** [review]
Looks fine to me, but WE ARE NOT MERGING THIS RIGHT NOW. Need to make a plan around the time of the next production of CAF files.

**Review by ikatza — COMMENTED** [review]
Some missing comments on `SRTrueInteractions`

**Comment by etyley** [comment]
So I have not had the time to go through every line and check the implementation to fill in the units. Although I think that is worth doing, it goes beyond the scope of this PR. A larger audit of the code should probably be performed at some point down the line to address the documentation and issues around setting defaults etc.

**Review by cjbackhouse — APPROVED** [review]
This is fine. It should go in at the same time as the related PRs in sbncode and sbnana. I think we agreed yesterday that this would target next week's release?

**Pull request merged**
