### PR TITLE
adding missing GEANT processes to CAFs

### PR DESCRIPTION
**Pull request by jzennamo**
Requires: https://github.com/SBNSoftware/sbncode/pull/215

### CODE REVIEW

**Review by cjbackhouse — APPROVED** [review]

**Review by PetrilloAtWork — CHANGES_REQUESTED** [review]
My comment was already touched in the twin pull request.
If `kG4UNKNOWN` is a valid value which get serialized, people using the new code will find that all their unknown processes are now multiple scattering. On the other end, it appears that the code considers not knowing a code an error, although not fatal, so should  we assume no data has the value `61` as process?
As a side note, this is the only enumerator here that does not have the "unknwon" value as `-1`; if it is acceptable to change `kG4UNKNOWN`, `-1` may be a better value than `63`, in which case I'd rather skip `63` as a transition value.

I am blocking the pull request as a way to elicit comments — as described above, chances are that the pull request is also fine as it is.

**Comment by jzennamo** [comment]
@wesketchum is making this change where he is going to make kG4UNKNOWN  = UINT_MAX, I think he is testing it first

**Comment by cjbackhouse** [comment]
Agree with using some other more reasonable value for `kG4UNKNOWN`. I don't think skipping `63` is particularly necessary, since this enum was already extended once previously in the relatively recent past. I would say we are at an early enough phase in the experiment that we should just do the right thing for the future without worrying too much about compatibility.

**Review by PetrilloAtWork — APPROVED** [review]

**Comment by PetrilloAtWork** [comment]
Ok, we are on the same page!


> @wesketchum is making this change where he is going to make kG4UNKNOWN = UINT_MAX, I think he is testing it first

I'd have chosen `-1`: easier to write, consistent with the other enumerators (on the other end, GCC enumerators are secretly unsigned...).

**Pull request merged**
