### PR TITLE
adding a missing g4 process

### PR DESCRIPTION
**Pull request by jzennamo**
Needed to add a missing G4 process as part of the migration to the new LArG4

### CODE REVIEW

**Comment by jzennamo** [comment]
This needs to be paired with https://github.com/SBNSoftware/sbncode/pull/167

**Review by wesketchum — COMMENTED** [review]
This looks very odd to have a declared number _after_ `kG4UNKNOWN`, but I also don't know if '60' is magic or not. Need @cjbackhouse to weigh in here I think.

**Comment by gputnam** [comment]
I agree -- I would put the new process before unknown. It's changed before, and 60 isn't hard coded anywhere.

**Comment by jzennamo** [comment]
fixed it and moved Unknown to 61

**Review by cjbackhouse — APPROVED** [review]
This looks fine. Agree about the ordering before kG4UNKNOWN. Probably it would have been better to make that zero in the past, but maybe we are stuck now?

**Review by wesketchum — APPROVED** [review]

**Pull request merged**
